[package]
name        = "flightdiff"
description = "Fast forensics for UAV flight logs."
default-run = "flightdiff"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
keywords.workspace     = true
categories.workspace   = true

[[bin]]
name = "flightdiff"
path = "src/main.rs"

[dependencies]
flightdiff-core = { path = "../flightdiff-core", version = "0.1.0" }
anyhow.workspace    = true
clap.workspace      = true
tracing.workspace   = true
tracing-subscriber.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
